### ISSUE TITLE
Differences In Ratings

### ISSUE THREAD

**Issue by jfgreco** [jasonfsmitty/krach#3]
Any idea why the ratings aren't matching up with the AHF official ratings?

**Comment by jasonfsmitty** [comment]
The simple answer I don't know exactly what algorithm they use.  This was all a bit of trial-and-error trying to get as close as possible, which is why there are so many command line options to tweak the parameters.

Some other things I'd like to investigate when I have the time:
 - #4 
 - #5 

When I started, one of the main questions I had was how are shootouts weighted ... when I asked someone in the league about it, they claimed shootouts count as normal wins/losses. But if I use that in my calculations I get numbers way off from what the AHF produces.  The only way for me to get fairly close is to treat all shootouts as a tie.  So either I was given bad information, or my tool is really far off from what the AHF uses.

Also, my tool seems to get closest if it iterates exactly 10 times.  If I let it run to full convergence the numbers are even farther off.  This has led me down a thought experiment where I try to imagine how someone without formal programming experience would go about trying to calculate the KRACH ratings.  My guess would be an Excel spreadsheet with each team in a row, and each column one iteration of the algorithm.  The first column would be the initial seed rating of 100 for all teams, and then 10 more columns, with each one feeding off of the column before it.  They'd probably use the (wins * losses / Sos) algorithm, and possibly only using integer data types.  The loss of precision from using integers rather than floating points might explain at least part of the mismatch in ratings.
