### ISSUE TITLE
KRACH Formula

### ISSUE THREAD

**Issue by jfgreco** [jasonfsmitty/krach#7]
https://atlantichockeyfederation.com/federation-krach-update/

They intend to publish the formula. Also indicated that there was an issue with shootouts. This might help get this closer.

**Comment by jasonfsmitty** [comment]
Awesome, thanks for the update!

**Comment by jfgreco** [comment]
https://atlantichockeyfederation.com/krach-explained/

**Comment by jasonfsmitty** [comment]
Finally had some time this weekend to dig into this proper.  The code referenced by the AHF (https://github.com/bjlkeng/Bradley-Terry-Model) requires some modifications to get the AHF results.  I'll create a fork with my changes for those interested.

This tool has been updated to properly mirror the AHF algorithm, and all of the standings have been re-calculated.  I'd like to update all of the documentation, but that may or or may not get done this weekend.

Note that even with the changes, there are still some minor differences.  In the 14U AA division (which has been my focus since that's where my son plays) most teams are identical to the AHF published numbers, but there are still 3 teams with different ratings.  Any tweaks I've tried to make have ripple changes through all teams, making the overall ratings more different.  For example, if I assume one of the games was entered wrong into the system and swap winner/loser, it'll ripple through the strength-of-schedule changing everyone's rating.

Once the remaining updates are done (docs for this tool, fork of the AHF tool) I'll communicate with the AHF and see if they can help me iron out the last few differences.

**Comment by jfgreco** [comment]
Thanks for the time you put in. I like you was only focusing on one division 10UB. Everything I looked at was pretty darn close. There were a handful that were off by a point. I wonder what is the differences in those cases.

**Comment by jfgreco** [comment]
Rank | Calc KRACH | AHF KRACH | +/- | Subdivision | Team | GP | W | L | SOW | SOL | T | SoS | Exp Wins | Win Diff
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 3195 | 3187 | -8 | Championship | Jersey Shore Wildcats Black | 17 | 16 | 0 | 0 | 0 | 1 | 181 | 16.8 | 0
2 | 1030 | 1029 | -1 | Championship | Philadelphia Jr. Flyers | 37 | 31 | 3 | 2 | 0 | 1 | 192 | 33.8 | 0
3 | 505 | 506 | 1 | Championship | Wissahickon Warriors Red | 37 | 28 | 7 | 0 | 1 | 1 | 324 | 28.8 | 0
4 | 221 | 221 | 0 | Championship | NJ Bandits Red | 17 | 10 | 6 | 0 | 0 | 1 | 698 | 10.8 | 0
5 | 197 | 198 | 1 | Gold | Haverford Hawks Schneider | 37 | 24 | 12 | 0 | 0 | 1 | 391 | 24.9 | 0
6 | 163 | 163 | 0 | Gold | Igloo Jaguars | 39 | 25 | 10 | 2 | 1 | 1 | 238 | 27.9 | 0
7 | 159 | 159 | 0 | Gold | Frederick Freeze | 17 | 12 | 3 | 1 | 0 | 1 | 155 | 13.9 | 0
8 | 117 | 117 | 0 | Gold | Hollydell Hurricanes | 37 | 25 | 8 | 1 | 2 | 1 | 181 | 26.9 | 0
9 | 96 | 96 | 0 | Silver | Delaware Ducks Black | 37 | 20 | 14 | 1 | 1 | 1 | 171 | 21.9 | 0
10 | 90 | 88 | -2 | Silver | York Devils | 37 | 23 | 10 | 3 | 0 | 1 | 116 | 26.9 | 0
11 | 86 | 86 | 0 | Silver | Royals Gray | 37 | 24 | 12 | 0 | 0 | 1 | 184 | 24.9 | 0
12 | 77 | 78 | 1 | Silver | North Jersey Sportscare Kings Yellow | 17 | 6 | 9 | 1 | 0 | 1 | 536 | 7.9 | 0
13 | 55 | 55 | 0 | Bronze | Valley Forge Colonials 10U B Skelton | 37 | 15 | 19 | 1 | 1 | 1 | 353 | 16.9 | 0
14 | 47 | 47 | 0 | Bronze | Southern Maryland Sabres 10U Black | 17 | 9 | 7 | 0 | 0 | 1 | 61 | 9.9 | 0
15 | 37 | 37 | 0 | Bronze | Royals Gold | 37 | 15 | 18 | 0 | 3 | 1 | 300 | 15.9 | 0
16 | 34 | 35 | 1 | Bronze | Lehigh Valley Phantoms | 37 | 19 | 13 | 1 | 3 | 1 | 150 | 20.9 | 0
17 | 20 | 20 | 0 |   | Lancaster Firebirds | 38 | 10 | 25 | 1 | 1 | 1 | 167 | 11.9 | 0
18 | 20 | 20 | 0 |   | Team Philadelphia | 37 | 13 | 22 | 0 | 1 | 1 | 85 | 13.9 | 0
19 | 18 | 18 | 0 |   | Haverford Hawks Wharton | 37 | 15 | 21 | 0 | 0 | 1 | 138 | 15.9 | 0
20 | 16 | 16 | 0 |   | Jersey Shore Wildcats Red | 17 | 7 | 9 | 0 | 0 | 1 | 46 | 7.9 | 0
22 | 14 | 15 | 1 |   | MYHA 10U B Blue | 17 | 3 | 13 | 0 | 0 | 1 | 129 | 3.9 | 0
21 | 14 | 14 | 0 |   | Tomorrow's Ice North Stars White | 17 | 6 | 10 | 0 | 0 | 1 | 45 | 6.9 | 0
23 | 12 | 12 | 0 |   | Maryland Jr Black Bears Red | 17 | 3 | 13 | 0 | 0 | 1 | 125 | 3.9 | 0
24 | 9 | 0 | -9 |   | Rockets Hockey Club White | 37 | 7 | 28 | 1 | 0 | 1 | 480 | 8.9 | 0
25 | 8 | 8 | 0 |   | NJ Bandits White | 17 | 5 | 11 | 0 | 0 | 1 | 69 | 5.9 | 0
26 | 7 | 7 | 0 |   | Wissahickon Warriors White | 37 | 11 | 25 | 0 | 0 | 1 | 62 | 11.9 | 0
27 | 5 | 5 | 0 |   | Grundy Senators | 37 | 7 | 28 | 1 | 0 | 1 | 98 | 8.9 | 0
28 | 3 | 4 | 1 |   | Philadelphia Blazers | 37 | 5 | 27 | 1 | 3 | 1 | 157 | 6.9 | 0
29 | 0 | 0 | 0 |   | Valley Forge Colonials 10U B Malik | 37 | 0 | 36 | 0 | 0 | 1 | 124 | 0.9 | 0
